Item.create(name: "Small Food", item_type: "food", effectiveness: 2, price: 12)
Item.create(name: "Big Food", item_type: "food", effectiveness: 4, price: 30)
Item.create(name: "Squeeky Toy", item_type: "toy", effectiveness: 2, price: 22)
Item.create(name: "Ball", item_type: "toy", effectiveness: 4, price: 40)
Item.create(name: "Medicine", item_type: "medicine", effectiveness: 5, price: 100)
